apiVersion: v2
name: payload-processing
description: A Helm chart for the payload processing

type: application

version: 0.1.0

appVersion: "0.2.0"

dependencies:
  - name: body-based-routing
    repository: oci://registry.k8s.io/gateway-api-inference-extension/charts
    version: v1.5.0-rc.1
    # Upstream chart; overrides go under upstreamBbr in this chart’s values.yaml.
    alias: upstreamBbr
