upstreamIpp:
  payloadProcessor:
    name: payload-processing
    replicas: 1
    image:
      registry: quay.io/opendatahub
      repository: odh-ai-gateway-payload-processing
      tag: odh-stable
      pullPolicy: IfNotPresent
    port: 9004
    healthCheckPort: 9005
    multiNamespace: true
    flags:
      v: 3
    customConfig:
      plugins:
      - type: body-field-to-header
        name: model-extractor
        parameters:
          fieldName: model
          headerName: X-Gateway-Model-Name
      - type: model-provider-resolver
      - type: api-translation
      - type: apikey-injection
      profiles:
      - name: default
        plugins:
          request:
          - pluginRef: model-extractor
          - pluginRef: model-provider-resolver
          - pluginRef: api-translation
          - pluginRef: apikey-injection
          response:
          - pluginRef: api-translation

  provider:
    name: istio

  inferenceGateway:
    name: maas-default-gateway
